package com.yoon.eiheihei.domain;

import java.io.Serializable;

public class EiVideo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eiheihei..ei_video.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eiheihei..ei_video.VIDEO_NAME
     *
     * @mbg.generated
     */
    private String videoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eiheihei..ei_video.VIDEO_URL
     *
     * @mbg.generated
     */
    private String videoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eiheihei..ei_video.SUFFIXS
     *
     * @mbg.generated
     */
    private String suffixs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eiheihei..ei_video
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eiheihei..ei_video.ID
     *
     * @return the value of eiheihei..ei_video.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eiheihei..ei_video.ID
     *
     * @param id the value for eiheihei..ei_video.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eiheihei..ei_video.VIDEO_NAME
     *
     * @return the value of eiheihei..ei_video.VIDEO_NAME
     *
     * @mbg.generated
     */
    public String getVideoName() {
        return videoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eiheihei..ei_video.VIDEO_NAME
     *
     * @param videoName the value for eiheihei..ei_video.VIDEO_NAME
     *
     * @mbg.generated
     */
    public void setVideoName(String videoName) {
        this.videoName = videoName == null ? null : videoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eiheihei..ei_video.VIDEO_URL
     *
     * @return the value of eiheihei..ei_video.VIDEO_URL
     *
     * @mbg.generated
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eiheihei..ei_video.VIDEO_URL
     *
     * @param videoUrl the value for eiheihei..ei_video.VIDEO_URL
     *
     * @mbg.generated
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eiheihei..ei_video.SUFFIXS
     *
     * @return the value of eiheihei..ei_video.SUFFIXS
     *
     * @mbg.generated
     */
    public String getSuffixs() {
        return suffixs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eiheihei..ei_video.SUFFIXS
     *
     * @param suffixs the value for eiheihei..ei_video.SUFFIXS
     *
     * @mbg.generated
     */
    public void setSuffixs(String suffixs) {
        this.suffixs = suffixs == null ? null : suffixs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eiheihei..ei_video
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EiVideo other = (EiVideo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getVideoName() == null ? other.getVideoName() == null : this.getVideoName().equals(other.getVideoName()))
            && (this.getVideoUrl() == null ? other.getVideoUrl() == null : this.getVideoUrl().equals(other.getVideoUrl()))
            && (this.getSuffixs() == null ? other.getSuffixs() == null : this.getSuffixs().equals(other.getSuffixs()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eiheihei..ei_video
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getVideoName() == null) ? 0 : getVideoName().hashCode());
        result = prime * result + ((getVideoUrl() == null) ? 0 : getVideoUrl().hashCode());
        result = prime * result + ((getSuffixs() == null) ? 0 : getSuffixs().hashCode());
        return result;
    }
}